In [2]:
%load_ext autoreload
%autoreload 2

In [ ]:
import torch
import numpy as np
# import torch.optim as optim


import numpy as np


from utilities import sample_images, get_empirical_latent_distribution, calculate_kl_divergence_with_HFM

from find_gauge import return_goodgauged_empirical_probs



In [5]:
device = torch.device('cpu')

In [7]:
from find_gauge import flip_gauge_bits, get_feature_frequencies_sorted, reorder_bit_states_by_frequency, return_goodgauged_empirical_probs
from utilities import get_m_s

In [9]:
debug_dict = {(1,1,0,1,0,0): 0.1,
              (0,1,0,1,0,1): 0.3,
              (1,0,0,1,1,1): 0.2,
              (1,0,1,1,0,1): 0.1,
              (1,0,1,1,1,1): 0.1,
              (1,0,1,1,0,0): 0.1,
              (0,1,0,1,1,0): 0.05,
              (0,1,0,1,0,0): 0.05}

good_gauged_dict = return_goodgauged_empirical_probs(debug_dict)
print("Good Gauged Dictionary:", good_gauged_dict)

Feature frequencies: [0.625 0.5   0.375 0.    0.375 0.5  ], Sorted indices: [0 1 5 2 4 3]
Good Gauged Dictionary: {(1, 0, 1, 0, 0, 0): 0.1, (0, 0, 0, 0, 0, 0): 0.3, (1, 1, 0, 0, 1, 0): 0.2, (1, 1, 0, 1, 0, 0): 0.1, (1, 1, 0, 1, 1, 0): 0.1, (1, 1, 1, 1, 0, 0): 0.1, (0, 0, 1, 0, 1, 0): 0.05, (0, 0, 1, 0, 0, 0): 0.05}


In [ ]:
debug_dict = {(1,1,0,1,0,0): 0.1,
              (0,1,0,1,0,1): 0.3,
              (1,0,0,1,1,1): 0.2,
              (1,0,1,1,0,1): 0.2,
              (1,0,1,1,1,1): 0.2}

good_gauged_dict = return_goodgauged_empirical_probs(debug_dict)
print("Good Gauged Dictionary:", good_gauged_dict)


def get_m_s(state_tuple, active_category_is_zero=True):
    """
    Calculates m_s for a given state tuple, 1-indexed.
    m_s is the index of the last active neuron.
    If active_category_is_zero is True, 'active' is represented by 0, the first category.
    If no neuron is active, m_s is 0.
    """
    active_val = 0 if active_category_is_zero else 1
    for i in reversed(range(len(state_tuple))):
        if state_tuple[i] == active_val:
            return i + 1  # 1-indexed
    return 0

first_key = list(good_gauged_dict.keys())[3]
print(first_key)

print(get_m_s(first_key, active_category_is_zero=False))

g, max_m_s = find_optimal_g_parameter(good_gauged_dict)
print("Optimal g parameter:", g)


In [ ]:
from find_gauge import flip_gauge_bits, get_feature_frequencies_sorted

In [ ]:
debug_dict = {(1,1,0,1,0,0): 0.1,
              (0,1,0,1,0,1): 0.3,
              (1,0,0,1,1,1): 0.2,
              (1,0,1,1,0,1): 0.2,
              (1,0,1,1,1,1): 0.2}

flipped_dict = flip_gauge_bits(debug_dict)
print("Flipped Dictionary:", flipped_dict)
get_feature_frequencies_sorted(flipped_dict)


In [10]:
from itertools import permutations

In [16]:
a = np.random.randint(0,10, size = (3, 6))


print("Original array:")
print(a)

number_of_columns = a.shape[1]
sdf = number_of_columns // 2
columns_to_permutate = np.arange((number_of_columns//2), number_of_columns)
permutations_list = list(permutations(columns_to_permutate))

permutations_list = list(permutations(range(number_of_columns)))
for perm in permutations_list:
    states_matrix_copy = np.empty(a.shape)
    states_matrix_copy[:, :] = a[:, list(perm)]
    print("Permuted array with columns:")
    print(list(perm))
    print(states_matrix_copy)


Original array:
[[3 5 6 3 7 7]
 [5 3 5 9 1 3]
 [5 9 2 5 4 3]]
Permuted array with columns:
[0, 1, 2, 3, 4, 5]
[[3. 5. 6. 3. 7. 7.]
 [5. 3. 5. 9. 1. 3.]
 [5. 9. 2. 5. 4. 3.]]
Permuted array with columns:
[0, 1, 2, 3, 5, 4]
[[3. 5. 6. 3. 7. 7.]
 [5. 3. 5. 9. 3. 1.]
 [5. 9. 2. 5. 3. 4.]]
Permuted array with columns:
[0, 1, 2, 4, 3, 5]
[[3. 5. 6. 7. 3. 7.]
 [5. 3. 5. 1. 9. 3.]
 [5. 9. 2. 4. 5. 3.]]
Permuted array with columns:
[0, 1, 2, 4, 5, 3]
[[3. 5. 6. 7. 7. 3.]
 [5. 3. 5. 1. 3. 9.]
 [5. 9. 2. 4. 3. 5.]]
Permuted array with columns:
[0, 1, 2, 5, 3, 4]
[[3. 5. 6. 7. 3. 7.]
 [5. 3. 5. 3. 9. 1.]
 [5. 9. 2. 3. 5. 4.]]
Permuted array with columns:
[0, 1, 2, 5, 4, 3]
[[3. 5. 6. 7. 7. 3.]
 [5. 3. 5. 3. 1. 9.]
 [5. 9. 2. 3. 4. 5.]]
Permuted array with columns:
[0, 1, 3, 2, 4, 5]
[[3. 5. 3. 6. 7. 7.]
 [5. 3. 9. 5. 1. 3.]
 [5. 9. 5. 2. 4. 3.]]
Permuted array with columns:
[0, 1, 3, 2, 5, 4]
[[3. 5. 3. 6. 7. 7.]
 [5. 3. 9. 5. 3. 1.]
 [5. 9. 5. 2. 3. 4.]]
Permuted array with columns:
[0, 1, 3, 4, 

In [ ]:
print(a.shape[1])
perms = permutations(range(a.shape[1]))
for perm in perms:
    print(perm, 6)
    print("-----")

# Matrix of states


In [19]:
# Suppose 'matrix' has been modified and has the same number of rows as debug_dict
debug_dict = {(1,1,0,1,0,0): 0.1,
              (0,1,0,1,0,1): 0.3,
              (1,0,0,1,1,1): 0.2,
              (1,0,1,1,0,1): 0.2,
              (1,0,1,1,1,1): 0.2}
matrix = np.array(list(debug_dict.keys()))
new_keys = [tuple(row) for row in matrix]
new_debug_dict = dict(zip(new_keys, debug_dict.values()))
print(matrix)
print(debug_dict.keys())



[[1 1 0 1 0 0]
 [0 1 0 1 0 1]
 [1 0 0 1 1 1]
 [1 0 1 1 0 1]
 [1 0 1 1 1 1]]
dict_keys([(1, 1, 0, 1, 0, 0), (0, 1, 0, 1, 0, 1), (1, 0, 0, 1, 1, 1), (1, 0, 1, 1, 0, 1), (1, 0, 1, 1, 1, 1)])


In [43]:
from utilities import calculate_kl_divergence_with_HFM_new


def find_minimum_kl_brute_force(good_guaged_probs, g=np.log(2), return_additional_info=False):
    """
    Brute-force search for the permutation of state columns that minimizes the KL divergence
    between the permuted empirical distribution and the HFM model with parameter g.

    Args:
        good_guaged_probs (dict): Dictionary mapping state tuples to probabilities.
        g (float, optional): HFM model parameter. Defaults to np.log(2).
        return_additional_info (bool, optional): If True, returns the best permutation and state dict.

    Returns:
        minimum_kl (float): The minimum KL divergence found.
        best_permutation (tuple or None): The permutation that yields the minimum KL (if requested).
        best_state_dict (dict or None): The permuted state dictionary (if requested).
    """
    states_matrix = np.array(list(good_guaged_probs.keys()))
    state_len = states_matrix.shape[1]
    permutations_list = list(permutations(range(state_len)))

 
    minimum_kl = float('inf')
    best_permutation = None
    best_state_dict = None
    i=0


    for perm in permutations_list:
        i += 1

        states_matrix_copy = np.empty(states_matrix.shape)
        states_matrix_copy[:, :] = states_matrix[:, list(perm)]

        permutated_state_dict = dict((tuple(row), prob) for row, prob in zip(states_matrix_copy, good_guaged_probs.values()))

        temporary_kl = calculate_kl_divergence_with_HFM_new(permutated_state_dict, g=g)
        if temporary_kl < minimum_kl:
            minimum_kl = temporary_kl
            best_permutation = perm
            best_state_dict = permutated_state_dict


        if i % 1000 == 0:
            print(f"Processed {i} permutations, current minimum KL: {minimum_kl}, best permutation: {best_permutation}")

    
    if not return_additional_info:
        best_permutation = None
        best_state_dict = None

    return (minimum_kl, best_permutation, best_state_dict) if return_additional_info else minimum_kl




In [1]:
debug_dict = {(1,1,0,1,0,0): 0.1,
              (0,1,0,1,0,1): 0.3,
              (1,0,0,1,1,1): 0.2,
              (1,0,1,1,0,1): 0.2,
              (1,0,1,1,1,1): 0.2}

good_gauged_dict = return_goodgauged_empirical_probs(debug_dict)
minimum_kl = find_minimum_kl_brute_force(good_gauged_dict, g=np.log(2))

NameError: name 'return_goodgauged_empirical_probs' is not defined

In [45]:
print(minimum_kl)

tensor(2.2603)
